<a href="https://colab.research.google.com/github/clshu/numpy_stack/blob/main/Numpy_LP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Array vs List


In [1]:
import numpy as np

In [2]:
L = [1, 2, 3]
L

[1, 2, 3]

In [3]:
A = np.array(L)
A

array([1, 2, 3])

In [4]:
for e in L:
  print(e)

1
2
3


In [5]:
for e in A:
  print(e)

1
2
3


In [6]:
L.append(4)
L

[1, 2, 3, 4]

In [7]:
A.append(4)

AttributeError: ignored

In [9]:
L + [5] # cancatenation

[1, 2, 3, 4, 5]

In [11]:
A + np.array([4]) # broadcast addition. Illigal matahmatically.

array([5, 6, 7])

In [15]:
A + np.array([4, 5, 6]) # It's intelligentlly adding an array to another array of the same size.

array([5, 7, 9])

In [14]:
A + np.array([4, 5])

ValueError: ignored