<a href="https://colab.research.google.com/github/clshu/numpy_stack/blob/main/Numpy_LP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***Numpy***

# 2. Array vs List


In [1]:
import numpy as np

In [2]:
L = [1, 2, 3]
L

[1, 2, 3]

In [3]:
A = np.array(L)
A

array([1, 2, 3])

In [4]:
for e in L:
  print(e)

1
2
3


In [5]:
for e in A:
  print(e)

1
2
3


In [6]:
L.append(4)
L

[1, 2, 3, 4]

In [7]:
A.append(4)

AttributeError: ignored

In [8]:
L + [5] # cancatenation

[1, 2, 3, 4, 5]

In [9]:
A + np.array([4]) # broadcast addition. Illigal matahmatically.

array([5, 6, 7])

In [10]:
A + np.array([4, 5, 6]) # It's intelligentlly adding an array to another array of the same size.

array([5, 7, 9])

In [18]:
A + np.array([4, 5])

ValueError: ignored

In [19]:
2 * A

array([2, 4, 6])

In [20]:
2 * L

[1, 2, 3, 4, 1, 2, 3, 4]

In [21]:
L + L

[1, 2, 3, 4, 1, 2, 3, 4]

In [22]:
L2 = []
for e in L:
  L2.append(e + 3)
L2

[4, 5, 6, 7]

In [23]:
L2 = [e + 3 for e in L]
L2

[4, 5, 6, 7]

In [25]:
L ** 2

TypeError: ignored

In [26]:
L2 = [e ** 2 for e in L]
L2

[1, 4, 9, 16]

## numpy applies the mathmatical funtions element-wise

In [34]:
A ** 2

array([1, 4, 9])

In [29]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [30]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [31]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [32]:
np.tanh(A)

array([0.76159416, 0.96402758, 0.99505475])

### Conclusion: List is a data structure. numpy is designed to do math on that data structure.

# 3. The Dot Production


In [35]:
a = np.array([1, 2])
b = np.array([3, 4])

In [36]:
dot = 0
for e, f in zip(a, b):
  dot += e * f
dot

11

In [37]:
dot = 0
for i in range(len(a)):
  dot += a[i] * b[i]
dot

11

In [38]:
a * b

array([3, 8])

In [39]:
np.sum(a * b)

11

In [41]:
(a * b).sum()

11

In [43]:
np.dot(a, b)

11

In [45]:
a.dot(b)

11

In [46]:
a @ b

11

### Prodcut of a, b equals to magnitude of a times magnitude of b times cosin of the the angle between a and b

In [48]:
ameg = np.sqrt((a * a).sum())
ameg

2.23606797749979

In [49]:
np.linalg.norm(a)

2.23606797749979

In [51]:
cosangle = a.dot(b) / (np.linalg.norm(a) * np.linalg.norm(b))
cosangle

0.9838699100999074

In [52]:
angle = np.arccos(cosangle)
angle

0.17985349979247847

# 4. Speed Test


In [64]:
## speed comparison ##
from datetime import datetime
# Note: you can also use %timeit
a = np.random.randn(100)
b = np.random.randn(100)
T = 100000

def slow_dot_production(a, b):
  result = 0
  for e, f in zip(a, b):
    result += e * f
  return result

t0 = datetime.now()
for i in range(T):
  slow_dot_production(a, b)
dt1 = datetime.now() - t0

t0 = datetime.now()
for i in range(T):
  a.dot(b)
dt2 = datetime.now() - t0

print ("dt1/dt2(slow vs np)): ", dt1.total_seconds() / dt2.total_seconds())

def list_comp_dot_production(a, b):
  result = 0
  for i, value in enumerate(a):
    result += value * b[i]
  return result

t0 = datetime.now()
for i in range(T):
  list_comp_dot_production(a, b)
dt3 = datetime.now() - t0

print ("dt3/dt2(list comprehension vs np): ", dt3.total_seconds() / dt2.total_seconds())

print("slow_dot_production: ", slow_dot_production(a, b))
print("np dot production: ", a.dot(b))
print("list comprehension: ", list_comp_dot_production(a,b))

dt1/dt2(slow vs np)):  31.79175273125451
dt3/dt2(list comprehension vs np):  36.688599656571185
slow_dot_production:  -0.6844105152691969
np dot production:  -0.6844105152691978
list comprehension:  -0.6844105152691969




# 5. Matrics

### Not recommand np.matrix. It reqires a 2D array.



In [77]:
L = [[1, 2], [3, 4]]



In [74]:
L[0]


[1, 2]

In [75]:
L[0][1]

2

### np class methods can work with reqular arrays


In [76]:
np.exp(L)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [79]:
A = np.array(L)
A

array([[1, 2],
       [3, 4]])

In [80]:
A[0][1]

2

In [82]:
A[0, 1] # better feature

2

In [83]:
A[:0]

array([], shape=(0, 2), dtype=int64)

In [84]:
A.T

array([[1, 3],
       [2, 4]])

In [85]:
np.exp(A)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

### np treats a regular array as an np array and return results as an np array

In [86]:
np.exp(L)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [87]:
B = [[1, 2, 3], [4, 5, 6]]
B

[[1, 2, 3], [4, 5, 6]]

In [88]:
A.dot(B)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [89]:
A.dot(B.T)

AttributeError: ignored

In [90]:
np.linalg.det(A)

-2.0000000000000004

In [91]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [93]:
np.linalg.inv(A).dot(A)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [94]:
np.trace(A)

5

In [95]:
np.diag(A)

array([1, 4])

In [96]:
np.diag([1, 4])

array([[1, 0],
       [0, 4]])

In [98]:
np.linalg.eig(A)

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [99]:
Lam, V = np.linalg.eig(A)

In [100]:
V[:,0] * Lam[0] == A @ V[:,0]


array([ True, False])

In [101]:
V[:,0] * Lam[0], A @ V[:,0]

(array([ 0.30697009, -0.21062466]), array([ 0.30697009, -0.21062466]))

In [102]:
np.allclose(V[:,0] * Lam[0], A @ V[:,0])

True

In [103]:
np.allclose(V @ np.diag(Lam), A @ V)

True

# 6. Solving Linear System

In [108]:
# A park of entrance of 2200 persons, including children and adults. The total receipt is $5050
# A child's ticket price is $1.4 and an adult's price is $4. How many children and adults enter the park?


A = [[1, 1], [1.5, 4]]
b = [2200, 5050]



In [109]:
np.linalg.solve(A, b) # Good

array([1500.,  700.])

In [110]:
np.linalg.inv(A).dot(b) # Slow. Don't use it this way

array([1500.,  700.])