<a href="https://colab.research.google.com/github/clshu/numpy_stack/blob/main/Panda_LP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 2. Loading in Data

In [2]:
import pandas as pd

In [3]:
!wget https://raw.githubusercontent.com/lazyprogrammer/machine_learning_examples/master/tf2.0/sbux.csv

--2022-05-20 08:51:44--  https://raw.githubusercontent.com/lazyprogrammer/machine_learning_examples/master/tf2.0/sbux.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 61896 (60K) [text/plain]
Saving to: ‘sbux.csv’

sbux.csv            100%[===================>]  60.45K  --.-KB/s    in 0.01s   

2022-05-20 08:51:44 (5.45 MB/s) - ‘sbux.csv’ saved [61896/61896]



In [4]:
df = pd.read_csv('sbux.csv')

In [5]:
df = pd.read_csv('https://raw.githubusercontent.com/lazyprogrammer/machine_learning_examples/master/tf2.0/sbux.csv')

In [6]:
type(df)

pandas.core.frame.DataFrame

In [9]:
!head sbux.csv

date,open,high,low,close,volume,Name
2013-02-08,27.92,28.325,27.92,28.185,7146296,SBUX
2013-02-11,28.26,28.26,27.93,28.07,5457354,SBUX
2013-02-12,28.0,28.275,27.975,28.13,8665592,SBUX
2013-02-13,28.23,28.23,27.75,27.915,7022056,SBUX
2013-02-14,27.765,27.905,27.675,27.775,8899188,SBUX
2013-02-15,27.805,27.85,27.085,27.17,18195730,SBUX
2013-02-19,27.18,27.305,27.01,27.225,11760912,SBUX
2013-02-20,27.3,27.42,26.59,26.655,12472506,SBUX
2013-02-21,26.535,26.82,26.26,26.675,13896450,SBUX


In [10]:
df.head()

date    open    high     low   close   volume  Name
0  2013-02-08  27.920  28.325  27.920  28.185  7146296  SBUX
1  2013-02-11  28.260  28.260  27.930  28.070  5457354  SBUX
2  2013-02-12  28.000  28.275  27.975  28.130  8665592  SBUX
3  2013-02-13  28.230  28.230  27.750  27.915  7022056  SBUX
4  2013-02-14  27.765  27.905  27.675  27.775  8899188  SBUX

In [11]:
df.head(10)

date    open    high     low   close    volume  Name
0  2013-02-08  27.920  28.325  27.920  28.185   7146296  SBUX
1  2013-02-11  28.260  28.260  27.930  28.070   5457354  SBUX
2  2013-02-12  28.000  28.275  27.975  28.130   8665592  SBUX
3  2013-02-13  28.230  28.230  27.750  27.915   7022056  SBUX
4  2013-02-14  27.765  27.905  27.675  27.775   8899188  SBUX
5  2013-02-15  27.805  27.850  27.085  27.170  18195730  SBUX
6  2013-02-19  27.180  27.305  27.010  27.225  11760912  SBUX
7  2013-02-20  27.300  27.420  26.590  26.655  12472506  SBUX
8  2013-02-21  26.535  26.820  26.260  26.675  13896450  SBUX
9  2013-02-22  26.850  27.105  26.640  27.085  11487316  SBUX

In [12]:
df.tail()

date    open   high    low  close    volume  Name
1254  2018-02-01  56.280  56.42  55.89  56.00  14690146  SBUX
1255  2018-02-02  55.900  56.32  55.70  55.77  15358909  SBUX
1256  2018-02-05  55.530  56.26  54.57  54.69  16059955  SBUX
1257  2018-02-06  53.685  56.06  53.56  55.61  17415065  SBUX
1258  2018-02-07  55.080  55.43  54.44  54.46  13927022  SBUX

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1259 entries, 0 to 1258
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   date    1259 non-null   object 
 1   open    1259 non-null   float64
 2   high    1259 non-null   float64
 3   low     1259 non-null   float64
 4   close   1259 non-null   float64
 5   volume  1259 non-null   int64  
 6   Name    1259 non-null   object 
dtypes: float64(4), int64(1), object(2)
memory usage: 69.0+ KB


# 3. Selecting Rows and Columns

In [14]:
df.columns

Index(['date', 'open', 'high', 'low', 'close', 'volume', 'Name'], dtype='object')

In [15]:
df.columns = ['date', 'open', 'high', 'low', 'close', 'volume', 'Name']

In [16]:
df.head()

date    open    high     low   close   volume  Name
0  2013-02-08  27.920  28.325  27.920  28.185  7146296  SBUX
1  2013-02-11  28.260  28.260  27.930  28.070  5457354  SBUX
2  2013-02-12  28.000  28.275  27.975  28.130  8665592  SBUX
3  2013-02-13  28.230  28.230  27.750  27.915  7022056  SBUX
4  2013-02-14  27.765  27.905  27.675  27.775  8899188  SBUX

In [18]:
df['open']

0       27.920
1       28.260
2       28.000
3       28.230
4       27.765
         ...  
1254    56.280
1255    55.900
1256    55.530
1257    53.685
1258    55.080
Name: open, Length: 1259, dtype: float64

In [20]:
type(df['open'])

pandas.core.series.Series

In [19]:
df[['open', 'close']]

open   close
0     27.920  28.185
1     28.260  28.070
2     28.000  28.130
3     28.230  27.915
4     27.765  27.775
...      ...     ...
1254  56.280  56.000
1255  55.900  55.770
1256  55.530  54.690
1257  53.685  55.610
1258  55.080  54.460

[1259 rows x 2 columns]

In [21]:
type(df[['open', 'close']])

pandas.core.frame.DataFrame

In [22]:
df.iloc[0]

date      2013-02-08
open           27.92
high          28.325
low            27.92
close         28.185
volume       7146296
Name            SBUX
Name: 0, dtype: object

In [23]:
df.loc[0]

date      2013-02-08
open           27.92
high          28.325
low            27.92
close         28.185
volume       7146296
Name            SBUX
Name: 0, dtype: object

In [24]:
df2 = pd.read_csv('sbux.csv', index_col='date')

In [25]:
df2.head()

open    high     low   close   volume  Name
date                                                     
2013-02-08  27.920  28.325  27.920  28.185  7146296  SBUX
2013-02-11  28.260  28.260  27.930  28.070  5457354  SBUX
2013-02-12  28.000  28.275  27.975  28.130  8665592  SBUX
2013-02-13  28.230  28.230  27.750  27.915  7022056  SBUX
2013-02-14  27.765  27.905  27.675  27.775  8899188  SBUX

In [26]:
df2.loc['2013-02-08']

open        27.92
high       28.325
low         27.92
close      28.185
volume    7146296
Name         SBUX
Name: 2013-02-08, dtype: object

In [27]:
type(df2.loc['2013-02-08'])

pandas.core.series.Series

In [29]:
df[df['open'] > 64]

date   open    high    low  close   volume  Name
1087  2017-06-05  64.85  64.870  64.18  64.27  6809284  SBUX
1088  2017-06-06  64.22  64.350  64.05  64.16  5448439  SBUX
1089  2017-06-07  64.13  64.295  63.34  63.50  8364994  SBUX

In [31]:
df[df['Name'] != 'SBUX' ]

Empty DataFrame
Columns: [date, open, high, low, close, volume, Name]
Index: []

In [32]:
type(df['Name']) # Bracket selection is more consistent with row selection in numpy

pandas.core.series.Series

In [33]:
import numpy as np
A = np.arange(10)
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
A[A % 2 == 0]

array([0, 2, 4, 6, 8])

In [35]:
df.values

array([['2013-02-08', 27.92, 28.325, ..., 28.185, 7146296, 'SBUX'],
       ['2013-02-11', 28.26, 28.26, ..., 28.07, 5457354, 'SBUX'],
       ['2013-02-12', 28.0, 28.275, ..., 28.13, 8665592, 'SBUX'],
       ...,
       ['2018-02-05', 55.53, 56.26, ..., 54.69, 16059955, 'SBUX'],
       ['2018-02-06', 53.685, 56.06, ..., 55.61, 17415065, 'SBUX'],
       ['2018-02-07', 55.08, 55.43, ..., 54.46, 13927022, 'SBUX']],
      dtype=object)

In [37]:
A = df[['open', 'close']].values
A

array([[27.92 , 28.185],
       [28.26 , 28.07 ],
       [28.   , 28.13 ],
       ...,
       [55.53 , 54.69 ],
       [53.685, 55.61 ],
       [55.08 , 54.46 ]])

In [38]:
type(A)

numpy.ndarray

In [43]:
smalldf = df[['open', 'close']]
smalldf.to_csv('output.csv')

In [42]:
!head output.csv

,open,close
0,27.92,28.185
1,28.26,28.07
2,28.0,28.13
3,28.23,27.915
4,27.765,27.775
5,27.805,27.17
6,27.18,27.225
7,27.3,26.655
8,26.535,26.675


In [45]:
smalldf.to_csv('output.csv', index=False)

In [47]:
!head output.csv

open,close
27.92,28.185
28.26,28.07
28.0,28.13
28.23,27.915
27.765,27.775
27.805,27.17
27.18,27.225
27.3,26.655
26.535,26.675


# 3. The apply() function

In [48]:
def date_to_year(row):
  return int(row['date'].split('-')[0])

df.apply(date_to_year, axis=1) # axis=1 row-wise, axis=0 column-wise

0       2013
1       2013
2       2013
3       2013
4       2013
        ... 
1254    2018
1255    2018
1256    2018
1257    2018
1258    2018
Length: 1259, dtype: int64

In [49]:
df['year'] = df.apply(date_to_year, axis=1)

In [50]:
df.head()

date    open    high     low   close   volume  Name  year
0  2013-02-08  27.920  28.325  27.920  28.185  7146296  SBUX  2013
1  2013-02-11  28.260  28.260  27.930  28.070  5457354  SBUX  2013
2  2013-02-12  28.000  28.275  27.975  28.130  8665592  SBUX  2013
3  2013-02-13  28.230  28.230  27.750  27.915  7022056  SBUX  2013
4  2013-02-14  27.765  27.905  27.675  27.775  8899188  SBUX  2013